### ISSUE TITLE
jmalcantara@apunto.com.mx on build #5: Necesitamos una menú para seleccionar el distrito, enviaré…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/UIC#2]
Feedback from jmalcantara@apunto.com.mx : Necesitamos una menú para seleccionar el distrito, enviaré la lista por email

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/581247982f25120100f005c4/5812a0d17eef7e01000308a1/21ed2a5d-7335-462c-b18c-50191515cbc6.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Oct 31 2016 09:54:59 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>5</td></tr><tr><td>Device type</td><td>A0001</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>77% Charging</td></tr><tr><td>Memory free</td><td>324 MB / 2880 MB</td></tr></table>

 [Link to buddybuild feedback from build 5](https://dashboard.buddybuild.com/apps/581247982f25120100f005c4/feedback?fid=581714f3bbe62101009e8bdc&bnum=5)

**Comment by ifoche** [comment]
@jmalcantara ok, we can implement a dropdown menu instead of that free text. I'll keep this task in ready column until I will receive your district list.

**Comment by jmalcantara** [comment]
I'm going to send you an updated list to add an option for people born out of Zimbabwe. I'll send it by email with instructions on what the app should do when that option is selected.
Thanks

**Comment by ifoche** [comment]
ok, I've created an issue for that (#4). Can you please check an approve by moving them to done (or ready if it's not done) this issue and the issue #1?
