### ISSUE TITLE
New district option for people born outside ZW

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/UIC#4]

**Comment by ifoche** [comment]
@jmalcantara We will develop it, as soon as we will have the new option and it's associated new logic. Waiting for your email

**Comment by ifoche** [comment]
@jmalcantara thanks for sending the new option "Out of Zimbabwe". Should we understand that the 2 characters added to the code on this option selection are WE? Thanks

**Comment by jmalcantara** [comment]
Hi Ignacio
I just received the following information from the team in Zimbabwe
-District of Birth: for clients born outside of Zimbabwe, "Out" district should be selected in the dropdown = UT
So according to this we have to change the name of the option to just be "Out" and the same rule about the use of the last two characters applies.
Thanks!
JM

**Comment by ifoche** [comment]
Sure! I'll generate a new release with that change
