### ISSUE TITLE
jmalcantara@apunto.com.mx on build #10: Please remove the last paragraph, Janedoe is used only in…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/UIC#9]
Feedback from jmalcantara@apunto.com.mx : Please remove the last paragraph, Janedoe is used only in dhis 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/581247982f25120100f005c4/583c5c1b9c66310100574845/226f2bba-a068-4d8e-8a5b-17397daa5b21.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 18:40:07 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>A0001</td></tr><tr><td>Screen size</td><td>1080</td></tr><tr><td>Screen size</td><td>1080px by 1920px</td></tr><tr><td>Battery</td><td>73% Unplugged</td></tr><tr><td>Memory free</td><td>324 MB / 2880 MB</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/581247982f25120100f005c4/feedback?fid=583f1d07549cb00100ca524d&bnum=10)

**Comment by jmalcantara** [comment]
Thank you
